### PR TITLE
chore: use patternfly react layout

### PR DESCRIPTION
**Pull request by kahboom**
## Description
This PR updates the entire app to use the layout containing PatternFly React components, along with some other minor enhancements (see below).

## Changes

- Rename `/connectors` dir to `/(connectors)` so that it can be the default landing page for all subroutes without adding `/connectors` to the route (see [Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) if you are curious about how this works)
- Update default `page.tsx` to be the landing page (should be blank as of right now) and create an empty story for it
- Move `header` and `sidebar` into their own UI components, and create stories for them
- Add toggle functionality to the sidebar/header
- Add active route functionality to the sidebar
- Remove unused pages and stories

## Screenshots

`LayoutHeader` story:

LayoutHeader Story

`LayoutSidebar` story:

LayoutSidebar Story

Root `page.tsx` (as the Landing Page):

Landing Page

`SelectConnector` page

Select Connector Page

### CODE REVIEW

**Comment by shivamG640** [comment]
Hi @kahboom,
What do you mean by the toggle functionality to the sidebar/header?
Also I can not see the Chromatic builds here.

**Review by kumaradityaraj — APPROVED** [review]

**Comment by kahboom** [comment]
>What do you mean by the toggle functionality to the sidebar/header?
>Also I can not see the Chromatic builds here.

Hey @shivamG640 , by the "toggle functionality to the sidebar/header" I mean that you can collapse the sidebar from the header using the little burger icon here: https://651ecd1e3026bc6c081c82b9-etsduebesi.chromatic.com/?path=/story/components-layout-layoutheader--default. Actually, you remind me that the stories we have do not show this functionality so maybe I should add a story for the entire layout + page. But it looks like this:

Screen Shot 2023-10-19 at 12 08 03 pm

Screen Shot 2023-10-19 at 12 08 10 pm

You can test this from the PatternFly docs: https://patternfly-react.surge.sh/demos/card-view/

To view the Chromatic builds once they are finished it's a bit annoying and hidden, you have to click on "Show all checks" and then it shows them. Like this:

Screen Shot 2023-10-19 at 12 05 55 pm

Screen Shot 2023-10-19 at 12 06 05 pm

Maybe there is a better way to show them per PR, like a comment or something. I can try to find out, because it's not very obvious right now and easy to forget.

**Comment by shivamG640** [comment]
Thanks @kahboom for the clarification. But one last thing, why do we need a Collapsable Sidebar/header?
Is it because we need to hide it for the Canvas page?
#JustAsking

**Review by shivamG640 — APPROVED** [review]

**Comment by kahboom** [comment]
>why do we need a Collapsable Sidebar/header?
>Is it because we need to hide it for the Canvas page?
>#JustAsking

@shivamG640 - We don't really _need_ it but it's standard on PF layouts and is on the designs in the Miro board (except the only item in the sidebar is `Connectors`). We don't really have pages to put in there so we might as well be able to collapse it. However, I've started putting a link to each page on there for now to make it easy for development (until we have a wizard or whatever UXD team decide and then we can remove them later).

**Pull request merged**
